/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package toniPackage;

import Class.TableViews;
import Class.koneksi;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author root
 */
public class FormAsuhanKebidanan extends javax.swing.JInternalFrame {

    private final String dataku = null;
    private ResultSet res;
    TableViews TableViews = new TableViews();
    DefaultTableModel TableModels;
    JDesktopPane DP;
    private int id;
    private final String regid;
    private final String nomedrec;
    private final String nama;

    public FormAsuhanKebidanan(JDesktopPane DP, String regid, String nomedrec, String nama) {
        initComponents();
        this.DP = DP;
        this.regid = regid;
        this.nomedrec = nomedrec;
        this.nama = nama;
        defaultload();
        SettingTableModel();

    }

    private void deleteasuhan() {
        int row = tblAsuahan.getSelectedRow();
        String asuhan_id = tblAsuahan.getValueAt(row, 0).toString();
        try {
            TableModels.getDataVector().removeAllElements();
            String query = "DELETE FROM asuhankebidanan WHERE asuhan_id = ?";
            PreparedStatement statement = koneksi.getConnection().prepareStatement(query);
            statement.setString(1, asuhan_id);
            statement.executeUpdate();
            statement.close();

            TableModels.getDataVector().removeAllElements();
            SettingTableModel();

            JOptionPane.showMessageDialog(rootPane, "Data Berhasil Dihapus...");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus : " + ex);
        }

    }

    private void defaultload() {
        SettingTableModel();
        txtregid.setText(regid);
        txtnamapasien.setText(nama);
        txtnomedrec.setText(nomedrec);
        txtregid.setEnabled(false);
        txtnamapasien.setEnabled(false);
        txtnomedrec.setEnabled(false);
    }

    private void SettingTableModel() {
        TableModels = TableViews.getDefaultTableModel(new String[]{
            "id",
            "Tanggal/Jam",
            "Subjektif",
            "Objektif",
            "Analisa",
            "Penata Laksanaan",
            "Petugas Medis"
        },
                null, new int[]{}, null);
        tblAsuahan.setModel(TableModels);
        TableViews.table(tblAsuahan, new int[]{10,100, 150, 150, 150, 150, 100});
        tampil();
    }

    private void tampil() {
        try {
            TableModels.getDataVector().removeAllElements();
            String query = "SELECT * FROM asuhankebidanan where regid = ?";
            PreparedStatement statement = koneksi.getConnection().prepareStatement(query);
            statement.setString(1, regid);
            ResultSet r = statement.executeQuery();
            while (r.next()) {
                TableModels.addRow(new Object[]{
                    r.getString("asuhan_id"),
                    r.getString("tanggalbuat"),
                    r.getString("subjektif"),
                    r.getString("objektif"),
                    r.getString("analisa"),
                    r.getString("penatalaksaan"),
                    r.getString("petugasmedis")
                });
                tblAsuahan.setModel(TableModels);
            }
            statement.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        txtregid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btncarimasterpasien = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnomedrec = new javax.swing.JTextField();
        txtnamapasien = new javax.swing.JTextField();
        btnCetak = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btntambahAsuahan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAsuahan = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLayeredPane1.setLayout(new java.awt.FlowLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Asuhan Kebidanan");
        jLayeredPane1.add(jLabel1);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Psien"));
        jLayeredPane2.add(txtregid);
        txtregid.setBounds(130, 30, 190, 30);

        jLabel2.setText("Registrasi ID");
        jLayeredPane2.add(jLabel2);
        jLabel2.setBounds(20, 30, 100, 30);

        btncarimasterpasien.setText("Cari Pasien");
        btncarimasterpasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncarimasterpasienActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btncarimasterpasien);
        btncarimasterpasien.setBounds(500, 70, 120, 30);

        jLabel8.setText("No Medrec");
        jLayeredPane2.add(jLabel8);
        jLabel8.setBounds(330, 30, 70, 30);

        jLabel6.setText("Nama");
        jLayeredPane2.add(jLabel6);
        jLabel6.setBounds(20, 70, 70, 30);
        jLayeredPane2.add(txtnomedrec);
        txtnomedrec.setBounds(410, 30, 210, 30);
        jLayeredPane2.add(txtnamapasien);
        txtnamapasien.setBounds(130, 70, 190, 30);

        btnCetak.setText("Cetak Asuhan");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });
        jLayeredPane2.add(btnCetak);
        btnCetak.setBounds(393, 70, 100, 30);

        btntambahAsuahan.setText("Tambah Asuhan");
        btntambahAsuahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntambahAsuahanActionPerformed(evt);
            }
        });

        tblAsuahan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAsuahan);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btntambahAsuahan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntambahAsuahan)
                    .addComponent(btnHapus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Asuhan Kebidanan", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLayeredPane1)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncarimasterpasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncarimasterpasienActionPerformed
        pencarian_pasien carpas = new pencarian_pasien(DP);
        DP.add(carpas);
        carpas.show();
    }//GEN-LAST:event_btncarimasterpasienActionPerformed

    private void btntambahAsuahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntambahAsuahanActionPerformed
        if ("".equals(txtregid.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Data masih kosong");
        } else {
            tambah_asuhan layan = new tambah_asuhan(regid, nomedrec);
            layan.add(new JButton("click"));
            layan.add(new JTextField(20));
            layan.add(new JLabel("Label"));
            int jop = JOptionPane.showOptionDialog(null,
                    layan, "", JOptionPane.YES_NO_OPTION,
                    JOptionPane.PLAIN_MESSAGE, null,
                    new String[]{"Selesai"}, // this is the array
                    "default");
            if (jop == JOptionPane.YES_OPTION) {
                this.repaint();
                SettingTableModel();
            }
        }

    }//GEN-LAST:event_btntambahAsuahanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        deleteasuhan();
        SettingTableModel();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
        if(!(txtregid.getText()).equals("")){
            try {
                JasperDesign jd = JRXmlLoader.load(getClass().getResourceAsStream("/report/asuhanKebidanan.jrxml"));
                String c = "select * from "
                        + "asuhankebidanan a, master_medrec b "
                        + "where a.medrec_id=b.medrec_id and a.regid="+txtregid.getText();
                JRDesignQuery query = new JRDesignQuery();
                query.setText(c);
                System.out.println(c + "");
                jd.setQuery(query);
                JasperReport jr = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(jr, null, koneksi.getConnection());
                JasperViewer.viewReport(jp, false);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Data Registrasi Pasien Kosong");
        }
        
    }//GEN-LAST:event_btnCetakActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btncarimasterpasien;
    private javax.swing.JButton btntambahAsuahan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblAsuahan;
    private javax.swing.JTextField txtnamapasien;
    private javax.swing.JTextField txtnomedrec;
    private static javax.swing.JTextField txtregid;
    // End of variables declaration//GEN-END:variables
}
