/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistem_monitoring_mutasi_ri;

import Class.*;
import com.mysql.jdbc.PreparedStatement;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yulianakusumawati
 */
public class frmTransaksiKamar extends javax.swing.JInternalFrame {

    DefaultTableModel TableModels = new DefaultTableModel();
    TableViews TableViews = new TableViews();
    PreparedStatement preparestatement;
    ResultSet resultset;
    JDesktopPane DP;
    Structure query = new Structure();
    private ArInterface interfaceAr;

    public void setInterface(ArInterface a) {
        interfaceAr = a;
    }

    public frmTransaksiKamar(JDesktopPane DP) {
        initComponents();
        this.DP = DP;
        SettingTableModel();
        Data();
        Click();
    }

    private void Click() {
        jTable1.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() > 1) {
                    String a = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 1);
                    String b = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 2);
                    String c = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 3);
                    String d = (String) jTable1.getValueAt(jTable1.getSelectedRow(), 5);
                    interfaceAr.Getting(a, b, c, d, "", "");
                    dispose();
                }
            }
        });
    }

    private void ClearTable() {
        TableModels.getDataVector().removeAllElements();
        jTable1.repaint();
    }

    private void SettingTableModel() {
        TableModels = TableViews.getDefaultTableModel(new String[]{"No", "Tanggal Masuk", "Tanggal Keluar", "Default Harga", "Jumlah", "Total Harga", "Petugas Buat", "Tanggal Buat", "trxkamar_id", "Regid", "Kamar Id"}, null, null, null);
        jTable1.setModel(TableModels);
        TableViews.table(jTable1, new int[]{50, 150, 100, 150, 150, 150, 150, 150, 0, 0, 0});
    }

    private void Data() {
        Thread thread = new Thread(new RunData());
        thread.start();
    }

    private class RunData implements Runnable {

        @Override
        public void run() {
            try {
                ClearTable();

                String parameter = jTextField1.getText();

                preparestatement = (PreparedStatement) koneksi.getConnection().prepareStatement(query.TransaksiKamar());
                preparestatement.setString(1, "%" + parameter + "%");
                resultset = preparestatement.executeQuery();
                int n = 0;
                while (resultset.next()) {
                    n++;
                    Object[] object = new Object[jTable1.getColumnCount()];
                    object[0] = n;
                    object[1] = resultset.getString(4);
                    object[2] = resultset.getString(5);
                    object[3] = resultset.getString(8);
                    object[4] = resultset.getString(9);
                    object[5] = resultset.getString(10);
                    object[6] = resultset.getString(6);
                    object[7] = resultset.getString(7);
                    object[8] = resultset.getString(1);
                    object[9] = resultset.getString(2);
                    object[10] = resultset.getString(3);
                    TableModels.addRow(object);

                    Thread.sleep(10);
                }

            } catch (Exception e) {
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Transaksi Kamar");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cari.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Registrasi Id");

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Transaksi Kamar"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(10, 20, 850, 300);
        jLayeredPane3.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 470, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jLayeredPane3.getAccessibleContext().setAccessibleName("Tabel Transaksi Kamar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        Data();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Data();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
